### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'out_filename'

### ISSUE THREAD

**Issue by guillermo-carrasco** [tdb-alcorn/q2#1]
Hi,

Trying to reproduce the cart pole training scenario described in [here](https://q2.readthedocs.io/en/latest/#first-time-usage), I encountered the following error:

```
(python3)  ~/repos_and_code/reinforced_test ~> q2 train random --env gym.CartPole-v1 --episodes 10 --render
Traceback (most recent call last):
  File "/home/guillermo/.anaconda/envs/python3/bin/q2", line 11, in <module>
    sys.exit(main())
  File "/home/guillermo/.anaconda/envs/python3/lib/python3.6/site-packages/q2/tool.py", line 83, in main
    args.func(args)
  File "/home/guillermo/.anaconda/envs/python3/lib/python3.6/site-packages/q2/train/__init__.py", line 90, in main
    regimen.train(env_maker, state, args.num_epochs, args.episodes_per_epoch, test=args.test, render=args.render, bk2dir=args.bk2dir, out_filename=args.out_filename)
AttributeError: 'Namespace' object has no attribute 'out_filename'
```
Looking at [the code](https://github.com/tdb-alcorn/q2/blob/1283f4b247f120eb0dbb060d324886f1096cd260/q2/train/__init__.py#L90), seems like the CLI argument `out_filename` is not defined anywhere. 

_More info:_

*Python version*: `Python 3.6.5 :: Anaconda, Inc.`

*Reproduce*: Just follow the steps described [here](https://q2.readthedocs.io/en/latest/#first-time-usage) on a clean python  environment.

**Comment by tdb-alcorn** [comment]
Derp, that's dead code from a previous iteration. It should be fixed by 08003db. I have pushed up a patch version v0.1.4.

If you'd be willing to verify that v0.1.4 works for you I'd be super grateful!
(just `pip uninstall q2` then `pip install q2` then run `q2 train random --env gym.CartPole-v1 --episodes 10 --render` again)

**Comment by guillermo-carrasco** [comment]
`pip install --upgrade q2` did the job :slightly_smiling_face: 
```
(python3)  ~/repos_and_code/reinforced_test ~> q2 train random --env gym.CartPole-v1 --episodes 10 --render
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
2018-07-03 08:13:27.388676: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-07-03 08:13:27.401476: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_tensor.cc:170 : Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on checkpoints/RandomAgent.ckpt: Not found: checkpoints; No such
file or directory
Checkpoint file not found, skipping load
Running environment gym.CartPole-v1
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Episode: 0      Frame: 12       Reward: 1.00 / 12.00    Framerate: 125.16
Episode: 1      Frame: 12       Reward: 1.00 / 12.00    Framerate: 150.03
Episode: 2      Frame: 16       Reward: 1.00 / 16.00    Framerate: 137.71
Episode: 3      Frame: 14       Reward: 1.00 / 14.00    Framerate: 151.63
Episode: 4      Frame: 62       Reward: 1.00 / 62.00    Framerate: 95.88
Episode: 5      Frame: 18       Reward: 1.00 / 18.00    Framerate: 129.20
Episode: 6      Frame: 16       Reward: 1.00 / 16.00    Framerate: 146.31
Episode: 7      Frame: 14       Reward: 1.00 / 14.00    Framerate: 81.75
Episode: 8      Frame: 17       Reward: 1.00 / 17.00    Framerate: 153.90
Episode: 9      Frame: 15       Reward: 1.00 / 15.00    Framerate: 113.34
```
Perfect. thanks!

**Comment by tdb-alcorn** [comment]
Woohoo! Thanks again for the feedback
